### ISSUE TITLE
Upload to App Store [Error] Verify your bundle identifier

### ISSUE THREAD

**Issue by Vi-dot** [lukevear/qt-xcodeproj-embeded-frameworks#1]
Hello @lukevear 

Thanks for your script.
It works nice when I just want to test my app in iOS Simulator.

But when I would like to send it to App Store, I get an error when I try to upload the .ipa : 
**No suitable application records were found. Verify your bundle identifier 'com.amazonaws.sdk.ios.AWSCognitoIdentityProviderASF' is correct.**

I put more details in this [post : Qt Forum](https://forum.qt.io/topic/87782/ios-upload-to-app-store-embeded-framework-problem)

Do you have an idea ?

**Comment by lukevear** [comment]
HI @Vi-dot 

You're very welcome!

I can't say I have come across that issue before. What version of Qt are you building with?

**Comment by Vi-dot** [comment]
I'm building with the last one : Qt 10.0

**Comment by Vi-dot** [comment]
The steps are : 

1) I download the last aws-sdk-ios prebuilt frameworks > https://sdk-for-ios.amazonwebservices.com/latest/aws-ios-sdk.zip

2) Link it in qmake file : 
```qmake
LIBS += \
        -F$$LIB_ROOT/aws-ios-sdk-2/frameworks \
        -framework AWSCore \
        -framework AWSAuthCore \
        -framework AWSCognitoAuth \
        -framework AWSCognitoIdentityProvider \
        -framework AWSCognitoIdentityProviderASF
```

3) Use your script to embed frameworks
```bash
%{sourceDir}/ios/lib/qt-xcodeproj-embeded-frameworks/embed.py %{buildDir}/spareit.xcodeproj %{sourceDir}/ios/lib/aws-ios-sdk-2/frameworks/AWSCore.framework %{sourceDir}/ios/lib/aws-ios-sdk-2/frameworks/AWSAuthCore.framework %{sourceDir}/ios/lib/aws-ios-sdk-2/frameworks/AWSCognitoAuth.framework %{sourceDir}/ios/lib/aws-ios-sdk-2/frameworks/AWSCognitoIdentityProvider.framework %{sourceDir}/ios/lib/aws-ios-sdk-2/frameworks/AWSCognitoIdentityProviderASF.framework
```

4) Then I build xcode project, and inside, following those [steps](https://github.com/aws/aws-sdk-ios#frameworks) (for aws-sdk-ios prebuilt frameworks) : I add the last step **Build Phase** to strip frameworks.

5) In **Build Settings**, I switch "Enable bitcode" to "No"

6) Finally I launch Archive > Upload to App Store > ... (.ipa made) > Upload > ERROR 😨

**Comment by lukevear** [comment]
Thanks for the steps. One thing I'll ask you to try is using qmake to embed the frameworks (which is supported on Qt 5.10).

Looking at https://github.com/qt/qtbase/blob/a37dd93defd91b79fb6730d0ff0515a66a0d3972/qmake/generators/mac/pbuilder_pbx.cpp#L1129 it appears it is possible if you simply use:

```
QMAKE_BUNDLE_DATA += \
	$$LIB_ROOT/aws-ios-sdk-2/frameworks/AWSCore.framework \
	$$LIB_ROOT/aws-ios-sdk-2/frameworks/AWSAuthCore.framework \
	$$LIB_ROOT/aws-ios-sdk-2/frameworks/AWSCognitoAuth.framework \
	$$LIB_ROOT/aws-ios-sdk-2/frameworks/AWSCognitoIdentityProvider.framework \
	$$LIB_ROOT/aws-ios-sdk-2/frameworks/AWSCognitoIdentityProviderASF.framework
```

**Comment by Vi-dot** [comment]
Thanks for your help.
Finally I found the fix. It was because of something that has nothing to do with this topic. I mechanically edited a key in Info.plist ... I'll never touch again CFBundleExecutable :D
```
<key>CFBundleExecutable</key>
<string>$(EXECUTABLE_NAME)</string>
```

But about `QMAKE_BUNDLE_DATA` I tried it, and it doesn't make frameworks embeded.

**Comment by lukevear** [comment]
Oh! Well I'm glad it's all sorted.

Good to know about `QMAKE_BUNDLE_DATA` as well. I'll test myself and open a bug report with Qt.
